### ISSUE TITLE
Deployment Failed?

### ISSUE THREAD

**Issue by buchizo** [davidebbo-test/FunctionsSamples#1]
I tried deploy to Azure via this script. After deploy, deployment failed via deploy.azure.com. However I think deploy success on Azure.

![image](https://cloud.githubusercontent.com/assets/1254213/15452771/2401a2dc-2035-11e6-9e26-66f6671491bb.png)

![image](https://cloud.githubusercontent.com/assets/1254213/15452765/fb29b44e-2034-11e6-9396-efb4f7ee0354.png)

**Comment by davidebbo** [comment]
It was actually a bug in the Deploy site that I had fixed (https://github.com/projectkudu/slingshot/commit/736275dc6e16b9adecdb1fdef6f195bdcae15d6b), but in one region it had not been swapped to production. It is fixed now!
